### ISSUE TITLE
Hangs on iOS

### ISSUE THREAD

**Issue by ewinge** [scriptotek/realfagsbiblioteket-app#36] opened 2016-10-12 09:09 UTC
When clicking a book in the result list, the app hangs with the message "Laster..." and a spinner.
Platform: iOS

**Comment by danmichaelo** [comment] 2016-10-12 09:22
No good. I've actually had two reports of this issue before, just have forgotten to make an issue for it. So this seems to be a consistent (and serious!) issue we should prioritize to fix.

If I remember right I couldn't reproduce it in the simulator, and we don't have a test phone, so the first step for me is actually to find someone who are willing to donate their phone to me for some time..

**Comment by danmichaelo** [comment] 2016-12-02 22:05
Should be fixed in 2.3

**Closed as completed by danmichaelo** 2016-12-02 22:05 UTC
Labels: bug
